### PR TITLE
Fix keyword scope for static assert/if.

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Comment by infininight** [comment]
Perfect, thanks! :)

**Comment by jacob-carlborg** [comment]
May I ask why you're merging manually instead of using Github? The first thing I see when open this is that the PR is closed instead of merged. I'm starting to wonder why it's closed, then I go to the main project and see that it _is_ actually merged. Can be a bit confusing.

**Comment by infininight** [comment]
We prefer to keep a cleaner history rather than have the merge commits and forked history that using Github creates. That said this would have been a fast-forward and picked up by Github had I not been overly critical and removed a period from the subject line of your commit message. :)

**Comment by jacob-carlborg** [comment]
> We prefer to keep a cleaner history rather than have the merge commits and forked history that using Github creates.

Ok, I see. A bit unusual of how it normally works, but ok.

> That said this would have been a fast-forward and picked up by Github

As far as I know, Github always uses no-fast forward to always create a merge commit.

> had I not been overly critical and removed a period from the subject line of your commit message. :)

Hehe, I see. In future I can handle all adjustments to the code according to the feedback, that's kind of the point of pull requests :smiley:

**Comment by infininight** [comment]
> Ok, I see. A bit unusual of how it normally works, but ok.

We've always preferred this way, but a big benefit not is being able to have a clean/clear changeling automatically as part of the About window in TextMate (under bundles). For this reason I also merge pull requests into concise commits, etc. (While still keeping each commit to a logical single goal.)

> As far as I know, Github always uses no-fast forward to always create a merge commit.

Right, I always use the command line to manually process merges. If you do a simple fast-forward Github will recognize this and automatically close the pull request. Doesn't work though if I make any changes or if that are intervening commits which change the hash.

**Comment by jacob-carlborg** [comment]
Personally I prefer that the author of the pull request fixes the history according to the project's standards. The merge commits are trivially ignored using `git log --no-merges`. I'm going to stop arguing now and if merging manually is the standard here I'll accept that.

**Pull request closed without merging**
